### ISSUE TITLE
Is "bi-directional" possible?

### ISSUE THREAD

**Issue by brandonros** [shajunxing/quickjs-ffi#3]
It's easy with your library for QuickJS to call into .dylib / .so / .dll functions (normal FFI)

How would one of those DLLs for example, pass an event or variable back into QuickJS?

**Comment by shajunxing** [comment]
> 
> 
> It's easy with your library for QuickJS to call into .dylib / .so / .dll functions (normal FFI)
> 
> How would one of those DLLs for example, pass an event or variable back into QuickJS?

**Comment by shajunxing** [comment]
> 
> 
> It's easy with your library for QuickJS to call into .dylib / .so / .dll functions (normal FFI)
> 
> How would one of those DLLs for example, pass an event or variable back into QuickJS?

Yes it support ffi callback, you can pass a js function to dll as c function pointer, and later inside dll invoke it, it will actually invoke the js function.
