### ISSUE TITLE
error loading so file when running 'make'

### ISSUE THREAD

**Issue by hnuhchen** [shajunxing/quickjs-ffi#4]
![test](https://user-images.githubusercontent.com/29193431/136916579-3e9bb746-6327-459e-ac90-3cbb74a24c78.png)
I got errers when running `make`, i found that `quickjs-ffi.so` and `test-lib.so`  were generated, but could not be loaded, could you tell me how to solve the problem? 
Thank you

**Comment by shajunxing** [comment]
I'm not sure, maybe your libffi is outdated?
