### ISSUE TITLE
Would this compile with TCC ( https://bellard.org/tcc/ )?

### ISSUE THREAD

**Issue by xstos** [shajunxing/quickjs-ffi#7]
Hi Shajunxing, very cool work. I've been investigating creating my own really simple (educational) 3D software rendering engine based off something like http://blog.rogach.org/2015/08/how-to-create-your-own-simple-3d-render.html 

In order to do this, I need some C FFIs to make the GUI window and handle keyboard/mouse events and filesystem stuff (the existing ones are kinda complicated https://github.com/kaosat-dev/awesome-quickjs ) and I want to bind my C-written GUI functions with QuickJS using your FFI and use your wise philosophy of simple C and complex JS. I had a thought that your bindings would be super neat compiling in TCC, which has the ability to inject C scripts dynamically as well, making it scriptable on the C side and the JS side simultaneously. Hot reload could even be implemented this way too somehow.

Here's an example of TCC compiling C code as an interpreter. The symmetry of using Fabrice Bellard's engines together simultaneously just seems right somehow :) https://github.com/xstos/apps/blob/5b61b61c7b78ebde7a92518ca61b2c21c427cfd5/playground/c/tcc-0.9.27-win64-bin/src/libtcc_test.c

Just wondering if you think it would be straightforward to swap out GCC for TCC and marry both of them together so they can "dogfood"/communicate with each other. Would be super cool to make a self-modifying runtime that compiles itself lol.

Cheers,

Chris

**Comment by shajunxing** [comment]
Hi, Chris. I've never used TCC before, but my code is quite simple, didn't use any GCC features, if you meet any compilation problem, just modify code by your self. But maybe the real challenge is using TCC to compile quickjs and libffi, I think.

**Comment by shajunxing** [comment]
Hi, Chris. I've never used tcc before, but my code is quite simple, didn't use any gcc features, if you meet any compilation problem, just modify code by your self. But maybe the real challenge is using tcc to compile libffi, I think.

**Comment by xstos** [comment]
Cool thanks. I will give it a shot!
